export default [
  {
    id: 101,
    cat: 'kiji',
    huntable: true,
    name: 'エゾライチョウ',
    desc: '',
    src: '/pics/ezoraicyo.jpg',
  },
  {
    id: 102,
    cat: 'kiji',
    huntable: true,
    name: 'ヤマドリ',
    desc: '',
    src: '/pics/yamadori.jpg',
  },
  {
    id: 103,
    cat: 'kiji',
    huntable: true,
    name: 'キジ',
    desc: '',
    src: '/pics/kiji.jpg',
  },
  {
    id: 104,
    cat: 'kiji',
    huntable: true,
    name: 'コジュケイ',
    desc: '',
    src: '/pics/kojyukei.jpg',
    grade: 2,
  },

  {
    id: 201,
    cat: 'kamo',
    huntable: true,
    name: 'ヨシガモ',
    desc: '',
    src: '/pics/yoshigamo.jpg',
  },
  {
    id: 202,
    cat: 'kamo',
    huntable: true,
    name: 'ヒドリガモ',
    desc: '',
    src: '/pics/hidorigamo.jpg',
  },
  {
    id: 203,
    cat: 'kamo',
    huntable: true,
    name: 'マガモ',
    desc: '',
    src: '/pics/magamo.jpg',
  },
  {
    id: 204,
    cat: 'kamo',
    huntable: true,
    name: 'カルガモ',
    desc: '',
    src: '/pics/karugamo.jpg',
  },
  {
    id: 205,
    cat: 'kamo',
    huntable: true,
    name: 'ハシビロガモ',
    desc: '',
    src: '/pics/hashibirogamo.jpg',
  },
  {
    id: 206,
    cat: 'kamo',
    huntable: true,
    name: 'オナガガモ',
    desc: '',
    src: '/pics/onagagamo.jpg',
  },
  {
    id: 207,
    cat: 'kamo',
    huntable: true,
    name: 'コガモ',
    desc: '',
    src: '/pics/kogamo.jpg',
  },
  {
    id: 208,
    cat: 'kamo',
    huntable: true,
    name: 'ホシハジロ',
    desc: '',
    src: '/pics/hoshihajiro.jpg',
  },
  {
    id: 209,
    cat: 'kamo',
    huntable: true,
    name: 'キンクロハジロ',
    desc: '',
    src: '/pics/kinkurohajiro.jpg',
  },
  {
    id: 210,
    cat: 'kamo',
    huntable: true,
    name: 'スズガモ',
    desc: '',
    src: '/pics/suzugamo.jpg',
  },
  {
    id: 211,
    cat: 'kamo',
    huntable: true,
    name: 'クロガモ',
    desc: '',
    src: '/pics/kurogamo.jpg',
  },

  {
    id: 301,
    cat: 'hato',
    huntable: true,
    name: 'キジバト',
    desc: '',
    src: '/pics/kijihato.jpg',
    grade: 2,
  },

  {
    id: 401,
    cat: 'u',
    huntable: true,
    name: 'カワウ',
    desc: '',
    src: '/pics/kawau.jpg',
  },

  {
    id: 501,
    cat: 'sagi',
    huntable: true,
    name: 'ゴイサギ',
    desc: '',
    src: '/pics/goizaki.jpg',
  },

  {
    id: 601,
    cat: 'kuina',
    huntable: true,
    name: 'バン',
    desc: '',
    src: '/pics/ban.jpg',
    grade: 2,
  },

  {
    id: 701,
    cat: 'shigi',
    huntable: true,
    name: 'ヤマシギ',
    desc: '',
    src: '/pics/yamashigi.jpg',
    grade: 2,
  },
  {
    id: 702,
    cat: 'shigi',
    huntable: true,
    name: 'タシギ',
    desc: '',
    src: '/pics/tashigi.jpg',
  },

  {
    id: 801,
    cat: 'karasu',
    huntable: true,
    name: 'ミヤマガラス',
    desc: '',
    src: '/pics/miyamakarasu.jpg',
  },
  {
    id: 802,
    cat: 'karasu',
    huntable: true,
    name: 'ハシボソガラス',
    desc: '',
    src: '/pics/hashibosokarasu.jpg',
  },
  {
    id: 803,
    cat: 'karasu',
    huntable: true,
    name: 'ハシブトガラス',
    desc: '',
    src: '/pics/hashibutokarasu.jpg',
  },

  {
    id: 901,
    cat: 'hiyodori',
    huntable: true,
    name: 'ヒヨドリ',
    desc: '',
    src: '/pics/hiyodori.jpg',
    grade: 2,
  },

  {
    id: 1001,
    cat: 'mukudori',
    huntable: true,
    name: 'ムクドリ',
    desc: '',
    src: '/pics/mukudori.jpg',
    grade: 2,
  },

  {
    id: 1101,
    cat: 'suzume',
    huntable: true,
    name: 'ニュウナイスズメ',
    desc: '',
    src: '/pics/nyunaisuzume.jpg',
    grade: 2,
  },
  {
    id: 1102,
    cat: 'suzume',
    huntable: true,
    name: 'スズメ',
    desc: '',
    src: '/pics/suzume.jpg',
    grade: 2,
  },

  {
    id: 2101,
    cat: 'inu',
    huntable: true,
    name: 'タヌキ',
    desc: '',
    src: '/pics/tanuki.jpg',
  },
  {
    id: 2102,
    cat: 'inu',
    huntable: true,
    name: 'キツネ',
    desc: '',
    src: '/pics/kitsune.jpg',
  },
  {
    id: 2103,
    cat: 'inu',
    huntable: true,
    name: 'ノイヌ',
    desc: '',
    src: '/pics/noinu.jpg',
  },

  {
    id: 2201,
    cat: 'neko',
    huntable: true,
    name: 'ノネコ',
    desc: '',
    src: '/pics/noneko.jpg',
  },

  {
    id: 2301,
    cat: 'itachi',
    huntable: true,
    name: 'テン',
    desc: '',
    src: '/pics/ten.jpg',
  },

  {
    id: 2401,
    cat: 'araiguma',
    huntable: true,
    name: 'アライグマ',
    desc: '',
    src: '/pics/araiguma.jpg',
  },

  {
    id: 2501,
    cat: 'kuma',
    huntable: true,
    name: 'ヒグマ',
    desc: '',
    src: '/pics/higuma.jpg',
  },

  {
    id: 2601,
    cat: 'jyakouneko',
    huntable: true,
    name: 'ハクビシン',
    desc: '',
    src: '/pics/hakubishin.jpg',
  },

  {
    id: 2701,
    cat: 'inoshishi',
    huntable: true,
    name: 'イノシシ',
    desc: '',
    src: '/pics/inoshishi.jpg',
  },

  {
    id: 2801,
    cat: 'nihonjika',
    huntable: true,
    name: 'ニホンジカ',
    desc: '',
    src: '/pics/nihonjika.jpg',
  },

  {
    id: 2901,
    cat: 'risu',
    huntable: true,
    name: 'タイワンリス',
    desc: '',
    src: '/pics/taiwanrisu.jpg',
    grade: 2,
  },
  {
    id: 2902,
    cat: 'risu',
    huntable: true,
    name: 'シマリス',
    desc: '',
    src: '/pics/shimarisu.jpg',
    grade: 2,
  },
  {
    id: 2903,
    cat: 'risu',
    huntable: false,
    name: 'ニホンリス',
    desc: '',
    src: '/pics/nihonrisu.jpg',
    grade: 2,
  },

  {
    id: 3001,
    cat: 'nutoria',
    huntable: true,
    name: 'ヌートリア',
    desc: '',
    src: '/pics/nutoria.jpg',
  },

  {
    id: 3101,
    cat: 'usagi',
    huntable: true,
    name: 'ユキウサギ',
    desc: '',
    src: '/pics/yukiusagi.jpg',
  },
  {
    id: 3102,
    cat: 'usagi',
    huntable: true,
    name: 'ウサギ',
    desc: '',
    src: '/pics/usagi.jpg',
  },
]
