export default [
  {
    id: 1,
    cat: 1,
    huntable: true,
    name: 'マガモ',
    desc: '',
    src: '/pics/magamo.jpg',
  },
  {
    id: 2,
    cat: 1,
    huntable: true,
    name: 'ヒドリガモ',
    desc: '',
    src: '/pics/hidorigamo.jpg',
  },
  {
    id: 3,
    cat: 1,
    huntable: true,
    name: 'オナガガモ',
    desc: '',
    src: '/pics/onagagamo.jpg',
  },
  {
    id: 4,
    cat: 1,
    huntable: true,
    name: 'ヨシガモ',
    desc: '',
    src: '/pics/yoshigamo.jpg',
  },
  {
    id: 5,
    cat: 1,
    huntable: true,
    name: 'カルガモ',
    desc: '',
    src: '/pics/karugamo.jpg',
  },
  {
    id: 6,
    cat: 1,
    huntable: true,
    name: 'ハシビロガモ',
    desc: '',
    src: '/pics/hashibirogamo.jpg',
  },
  {
    id: 7,
    cat: 1,
    huntable: true,
    name: 'バン',
    desc: '',
    src: '/pics/ban.jpg',
  },
]
